### ISSUE TITLE
readme里的例程能够用吗

### ISSUE THREAD

**Issue by LanQ** [zhuyu4839/zlgcan-driver#1]
我手里也是周立功双口200U，按照步骤操作
1. 发送时参数trans_type找不到
2. 接收时内容总是None (周立功自己的zcanpro工具正常打印数据)

想确认下这个工程目前是否能够正常使用？

**Comment by LanQ** [comment]
> 我手里也是周立功双口200U，按照步骤操作
> 
> 1. 发送时参数trans_type找不到
> 2. 接收时内容总是None (周立功自己的zcanpro工具正常打印数据)
> 
> 想确认下这个工程目前是否能够正常使用？

发送可以发了 因为没有指定canfd类型。
但是接收还是一直为None

**Comment by LanQ** [comment]
配置的问题 可以使用

**Comment by jesses2025smith** [comment]
例程是可用的  如果有问题可以加我wechat   oscillo_scope

LanQ ***@***.***> 于2023年1月18日周三 16:02写道：
