### ISSUE TITLE
无法单次发送模式，接收一直为CANFD？

### ISSUE THREAD

**Issue by hmf1235789** [zhuyu4839/zlgcan-driver#11]
1、改为ZCANCanTransType.SINGLE单次发送，bus.recv()依旧能接收到发送帧
![1](https://github.com/user-attachments/assets/9aba1d9b-7693-4833-8021-bb5ca43527c8)

2、用其他设备发送普通CAN帧，poll_received_messages接收也默认为CANFD，用self.device.ReceiveFD解析
![2](https://github.com/user-attachments/assets/20742780-3a35-476b-9ee1-260f78f86d2b)

**Comment by jesses2025smith** [comment]
对于问题1 我不明白你现在的通道回路是怎样的；
对于问题2 我觉得逻辑就应该是这样的
