### ISSUE TITLE
使用UDSoncan发送诊断服务后报错

### ISSUE THREAD

**Issue by mengya1** [zhuyu4839/zlgcan-driver#13]
Hi作者：
  目前使用zlgcan-USBCANFD-200U发送一帧应用报文是正常的，但是使用UDSoncan发送诊断报文会提示超时：Did not receive response in time. P2 timeout time has expired (timeout=1.000 sec)。
这是根据UDSoncan例子改的：
import time
import can
import isotp
import udsoncan.configs
from can.interfaces.zlgcan import ZCanTxMode, ZCANDeviceType
from udsoncan.client import Client
from udsoncan.connections import PythonIsoTpConnection
udsoncan.setup_logging()

isotp_params = {
    'stmin': 32,
    # Will request the sender to wait 32ms between consecutive frame. 0-127ms or 100-900ns with values from 0xF1-0xF9
    'blocksize': 8,  # Request the sender to send 8 consecutives frames before sending a new flow control message
    'wftmax': 0,  # Number of wait frame allowed before triggering an error
    'tx_data_length': 8,  # Link layer (CAN layer) works with 8 byte payload (CAN 2.0)
    'tx_data_min_length': None,
    'tx_padding': 0,  # Will pad all transmitted CAN messages with byte 0x00.
    'rx_flowcontrol_timeout': 1000,  # Triggers a timeout if a flow control is awaited for more than 1000 milliseconds
    'rx_consecutive_frame_timeout': 1000,
    # Triggers a timeout if a consecutive frame is awaited for more than 1000 milliseconds
    # 'squash_stmin_requirement': False,      # When sending, respect the stmin requirement of the receiver. If set to True, go as fast as possible.
    'max_frame_size': 4095,  # Limit the size of receive frame.
    'can_fd': False,  # Does not set the can_fd flag on the output CAN messages
    'bitrate_switch': False,  # Does not set the bitrate_switch flag on the output CAN messages
    'rate_limit_enable': False,  # Disable the rate limiter
    'rate_limit_max_bitrate': 1000000,
    # Ignored when rate_limit_enable=False. Sets the max bitrate when rate_limit_enable=True
    'rate_limit_window_size': 0.2,
    # Ignored when rate_limit_enable=False. Sets the averaging window size for bitrate calculation when rate_limit_enable=True
    'listen_mode': False,  # Does not use the listen_mode which prevent transmission.
}

uds_config = udsoncan.configs.default_client_config.copy()

bus = can.Bus(interface="zlgcan",channel=0,
              device_type=ZCANDeviceType.ZCAN_USBCANFD_200U,
              configs=[{'bitrate': 500000, 'resistance': 1},
                       {'bitrate': 500000, 'resistance': 1}])

notifier = can.Notifier(bus, [can.Printer()])  # Add a debug listener that print all messages

tp_addr = isotp.Address(isotp.AddressingMode.Normal_11bits, txid=0x772, rxid=0x77A)  # Network layer addressing scheme

stack = isotp.NotifierBasedCanStack(bus=bus, notifier=notifier, address=tp_addr,
                                    params=isotp_params)  # Network/Transport layer (IsoTP protocol). Register a new listenenr

conn = PythonIsoTpConnection(stack)  # interface between Application and Transport layer
with Client(conn, config=uds_config) as client:

    client.change_session(1)

bus.shutdown()

**Comment by mengya1** [comment]
使用Vector Canoe VN1640收发是正常的，请问下你有使用过这个库碰到过这个问题吗

**Comment by jesses2025smith** [comment]
> 使用Vector Canoe VN1640收发是正常的，请问下你有使用过这个库碰到过这个问题吗

新版本的udsoncan库没适配，目前自己在实现统一的uds协议，如要使用周立功的CAN，请使用[udsoncan](https://github.com/zhuyu4839/python-udsoncan/tree/mydev), 其实是因为周立功的CAN使用python时速度变慢了，你将udsoncan中检查p2超时时间加长点就行
