### ISSUE TITLE
性能优化/新接口

### ISSUE THREAD

**Issue by luojiaaoo** [zhuyu4839/zlgcan-driver#15]
1、zlg的发送接口可以批量发送，这样发送会更快，我建议单独做一个发送线程；
2、老接口canfd和can分开接收，在获取接收报文的时候存在时间问题，时间更晚的报文可能因为报文类型导致先被获取，ZLG对支持合并的设备添加了新接口ZCAN_Receive_Data（也就是接收CANFD报文的接口，同时可以获取can报文），可以更新下
PS: 周立功的老接口确实设计的不行

**Comment by luojiaaoo** [comment]
https://github.com/luojiaaoo/python-can-zlg
我直接用ctypes调用的DLL，可以参考下
不好意思，因为我看您是通过rust做的二次封装，我没能力给这个仓库提PR

**Comment by jesses2025smith** [comment]
我对比了一下性能，使用zcanpro发送的时候，500K波特率下峰值帧率大概每秒2800帧，使用原生rust程序调用峰值帧率大概每秒2300帧，由于工程目的是支持多种类型CAN卡，如果分CAN卡类型去适配变动较大，故目前没有计划
