### ISSUE TITLE
提示：Windows fatal exception: access violation  

### ISSUE THREAD

**Issue by mengya1** [zhuyu4839/zlgcan-driver#16]
你好作者：
在使用USBCAN-200U进行报文收发的过程中，有时会提示：Windows fatal exception: access violation 
错误指向zlg.py             self.device = zlgcan_open(device_type, device_index, derive)  这行
又碰到过这种问题嘛

**Comment by jesses2025smith** [comment]
应该是使用了32位的python，目前这个问题没处理，请使用main分支的代码

**Comment by mengya1** [comment]
64位的Python

**Comment by jesses2025smith** [comment]
代码是怎么写的

**Comment by mengya1** [comment]
import time
from can.interfaces.zlgcan import ZCANDeviceType
import can
# from can.interfaces.vector import VectorBus
def send_and_receive_can_message(arbitration_id, data, expected_arbitration_id, expected_data):
    # 初始化CAN总线
    try:
        bus = can.Bus(interface="zlgcan",
                      device_type=ZCANDeviceType.ZCAN_USBCANFD_200U,
                      configs=[{'bitrate': 500000, 'resistance': 1},
                               {'bitrate': 500000, 'resistance': 1}])
        # bus = can.interfaces.vector.canlib.VectorBus(app_name='pycan', channel=0,
        #                                              bitrate=500000, data_bitrate=2000000,
        #                                              fd=False)
    except Exception as e:
        print(f"Failed to initialize CAN bus: {e}")
        return None
    # 发送的消息
    request_msg = can.Message(
        arbitration_id=arbitration_id,
        data=data,
        dlc=len(data),
        channel=0,
        is_extended_id=False
    )
    # 发送消息
    try:
        bus.send(request_msg)
        print(f"Sent message: ID={request_msg.arbitration_id}, Data={data.hex()}")
    except Exception as e:
        print(f"Failed to send message: {e}")
        bus.shutdown()
        return None

    if not expected_data:
        bus.shutdown()
        return None
    # 接收超时时间
    timeout = 5  
    start_time = time.time()

    rec_msg = None
    # 循环查找接收到的报文
    while time.time() - start_time < timeout:

        try:
            rec_msg = bus.recv(10)  # 10毫秒超时
        except Exception as e:
            print(f"Error receiving message: {e}")
            break
        # 检查是否接收到消息且ID匹配
        if rec_msg is not None and rec_msg.arbitration_id == expected_arbitration_id:
            break  # 找到匹配的报文，退出循环

    bus.shutdown()
    return rec_msg
然后用Pytest测试框架，进行一些收发报文的测试

**Comment by mengya1** [comment]
另外我用的是rust-dev分支的代码

**Comment by jesses2025smith** [comment]
如你的代码 ，我这运行着没问题，+wx解决吧：oscillo_scope

**Comment by mengya1** [comment]
不好意思，我们上班登不了微信，有飞书或钉钉嘛。

**Comment by luojiaaoo** [comment]
可能你open了多次，zlg所有通道共享open

**Comment by zhuyu4839** [comment]
![image](https://github.com/user-attachments/assets/c28d402e-51df-4f5d-9efa-07e3d2bab5b0)
