### ISSUE TITLE
USBCAN-II无法使用

### ISSUE THREAD

**Issue by chenj31** [zhuyu4839/zlgcan-driver#3]
按官方DEMO配置方式为
'''
USBCAN-II Start Demo
'''
def can_I_start(zcanlib, device_handle, chn):
    ip = zcanlib.GetIProperty(device_handle)
    ret = zcanlib.SetValue(ip, str(chn) + "/baud_rate", "250000") #250Kbps
现有接口无法调用

**Comment by jesses2025smith** [comment]
是的 目前只针对USBCANFD做了适配 后期有时间再去适配其他的

**Comment by jesses2025smith** [comment]
已经添加了USBCAN支持, 同时对官方的Demo做了封装, 可以使用python-can
如果需要调用底层接口, 请参考项目根目录zlgcan.py中ZCanBus的init方法
