### ISSUE TITLE
请问支持CANFD-800U吗？

### ISSUE THREAD

**Issue by lixiaoxie** [zhuyu4839/zlgcan-driver#6]
800U 初始化时报错ZLG: ZCAN_OpenDevice failed!

**Comment by jesses2025smith** [comment]
windows下应该是支持的  但是手头上没设备测试 可以远程  加我 oscillo_scope

**Comment by jesses2025smith** [comment]
目前没有设备测试

**Comment by zhuyu4839** [comment]
CANFD-800U驱动已经添加

**Comment by jesses2025smith** [comment]
CANFD-800U驱动已经添加，`bitrate.cfg.yaml`下载地址[bitrate.cfg.yaml](https://github.com/zhuyu4839/zlgcan-driver-rs/blob/master/bitrate.cfg.yaml)
