### ISSUE TITLE
WINDOWS 环境下的 CANFD支持？

### ISSUE THREAD

**Issue by PeaceZhang** [zhuyu4839/zlgcan-driver#7]
你好，请问下WINDOWS环境下还未支持CANFD的支持吗？
我这边的设备是USBCANFD-800U, 目标波特率是仲裁区500K, 数据区2M

**Comment by jesses2025smith** [comment]
是支持的吧，您代码中具体配置是怎样的，通道开启后有报文时指示灯是什么状态
